import express from 'express';
import path from 'path';
import {fileURLToPath} from 'url';
import {getM1,marketSymbol} from './lib/marketData.js';
import {analyze} from './lib/analysis.js';
const app=express(),__dirname=path.dirname(fileURLToPath(import.meta.url)),PORT=process.env.PORT||3000;
const pairs=['EURUSD','EURJPY','GBPUSD','CADCHF','USDJPY','NZDCHF','USDPKR','USDINR','BTCUSD','XAUUSD'],horizons=[1,2,3,5,15];
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'Forex Falcon',marketDataConfigured:Boolean(process.env.TWELVE_DATA_API_KEY),timestamp:new Date().toISOString()}));
app.get('/api/config',(_q,r)=>r.json({title:'Next Candle Intelligence',pairs,horizons,minimumProbability:60,confidenceType:'heuristic-forward-test'}));
app.get('/api/analyze/:pair',async(q,r)=>{try{const pair=q.params.pair.toUpperCase(),horizon=Number(q.query.horizon||1);if(!pairs.includes(pair)||!horizons.includes(horizon))return r.status(400).json({error:'Invalid pair or horizon'});const candles=await getM1(pair,300);const result=analyze(candles,horizon);r.json({...result,pair,symbol:marketSymbol(pair),candleTime:candles.at(-1)?.time,dataPoints:candles.length,generatedAt:Date.now()});}catch(e){r.status(503).json({error:e.message});}});
app.get('/api/price/:pair',async(q,r)=>{try{const pair=q.params.pair.toUpperCase();if(!pairs.includes(pair))return r.status(400).json({error:'Invalid pair'});const candles=await getM1(pair,300),x=candles.at(-1);r.json({pair,price:x.close,time:x.time});}catch(e){r.status(503).json({error:e.message});}});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Forex Falcon running on port ${PORT}`));
