import express from 'express';
import path from 'path';
import {fileURLToPath} from 'url';
import {getStagedSnapshot,getSettlementPrice,getSettlementCandle,getBudget,marketSymbol} from './lib/marketData.js';
import {analyze} from './lib/analysis.js';
import {diagnoseLoss,applyLossContext,getLossContext} from './lib/lossLearning.js';
import {fuseDecision} from './lib/decisionFusion.js';
import {microstructureSupported,getMicrostructureSnapshot,getMicrostructureResearch,applyMicrostructure} from './lib/microstructure.js';
import {startForexTickStream,getForexTickConfirmation,applyForexTickConfirmation,getForexTickStatus,getForexLivePrice} from './lib/forexTicks.js';
import {startBackgroundResearch,getBackgroundResearch,getAllBackgroundResearch,setBackgroundHorizon,primeAllPairs,timeframeBundle} from './lib/backgroundResearch.js';

const app=express(),__dirname=path.dirname(fileURLToPath(import.meta.url)),PORT=process.env.PORT||3000;
const pairs=['EURUSD','EURJPY','GBPUSD','AUDJPY','AUDUSD','USDJPY','NZDCHF','USDPKR','USDINR','BTCUSD','XAUUSD'],horizons=[1,2,3,5,15],TARGET_SIGNALS=20,MIN_CONFIDENCE=57;
const sampleOffsets={1:[30000,20000,10000],2:[45000,30000,15000],3:[45000,30000,15000],5:[20000,10000,4000],15:[30000,15000,4000]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const engine={running:false,phase:'IDLE',pair:'EURUSD',horizon:1,runId:0,runSignals:0,targetSignals:TARGET_SIGNALS,history:[],lastAnalysis:null,lastError:null,lastLossReview:null,startedAt:null,pausedAt:null,nextRunAt:null,sampleNextAt:null,sampleStage:0,targetBoundary:null,snapshots:[],timer:null,busy:false,recoveryPending:null};
const researchRunner={timer:null,lastError:null,lastRunAt:null};

app.use(express.json());
app.use((req,res,next)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.set('Pragma','no-cache');res.set('Expires','0');next()});
app.use(express.static(path.join(__dirname,'public'),{etag:false,lastModified:false,maxAge:0}));
function publicState(){return{running:engine.running,phase:engine.phase,pair:engine.pair,horizon:engine.horizon,runId:engine.runId,runSignals:engine.runSignals,targetSignals:engine.targetSignals,history:engine.history,lastAnalysis:engine.lastAnalysis,lastError:engine.lastError,lastLossReview:engine.lastLossReview,recoveryPending:engine.recoveryPending,adaptiveContext:getLossContext(engine.pair,engine.horizon),startedAt:engine.startedAt,pausedAt:engine.pausedAt,nextRunAt:engine.nextRunAt,sampleNextAt:engine.sampleNextAt,sampleStage:engine.sampleStage,targetBoundary:engine.targetBoundary,serverTime:Date.now(),budget:getBudget(),microstructureEnabled:microstructureSupported(engine.pair),forexTicks:getForexTickStatus(),btcResearch:getMicrostructureResearch('BTCUSD'),backgroundResearch:getAllBackgroundResearch(),btcResearchRunner:{lastRunAt:researchRunner.lastRunAt,lastError:researchRunner.lastError}}}
function clearTimer(){if(engine.timer){clearTimeout(engine.timer);engine.timer=null}}
function nextFullBoundary(h){const span=h*60000,maxOffset=(sampleOffsets[h]||sampleOffsets[1])[0];return Math.ceil((Date.now()+maxOffset+500)/span)*span}
async function precisePrice(pair){const live=getForexLivePrice(pair,5000);if(live)return live;const x=await getSettlementPrice(pair);return{...x,source:'CANDLE_FALLBACK'}}
function scheduleRecovery(parent){if(parent.isRecovery||!engine.running||parent.pair!==engine.pair||parent.horizon!==engine.horizon)return;const boundary=parent.expiry;engine.recoveryPending={parentId:parent.id,pair:parent.pair,horizon:parent.horizon,direction:parent.direction,boundary};const delay=Math.max(0,boundary-Date.now()+80);setTimeout(()=>openRecovery(parent),delay)}
async function openRecovery(parent){const r=engine.recoveryPending;if(!r||r.parentId!==parent.id||!engine.running)return;engine.recoveryPending=null;if(engine.runSignals>=TARGET_SIGNALS)return;try{const x=await precisePrice(parent.pair);const s={id:`${engine.runId}-${parent.expiry}-R1`,runId:engine.runId,pair:parent.pair,horizon:parent.horizon,analysisTimeframe:parent.analysisTimeframe,direction:parent.direction,probability:parent.probability,qualityScore:parent.qualityScore??null,evidenceScore:parent.evidenceScore??null,signalBoundary:parent.expiry,entry:x.price,entrySource:x.source,entryBid:x.bid??null,entryAsk:x.ask??null,entryLocked:true,expiry:parent.expiry+parent.horizon*60000,result:'PENDING',regime:parent.regime,engine:`${parent.engine}+RECOVERY_R1`,features:{...(parent.features||{}),recovery:true,recoveryStep:1,recoveryParentId:parent.id},quotexRule:true,isRecovery:true,recoveryStep:1,recoveryParentId:parent.id};engine.history.unshift(s);engine.history=engine.history.slice(0,20);engine.runSignals++;scheduleSettlement(s)}catch(e){engine.lastError=`Recovery entry failed: ${e.message}`}}
function resolvePending(price,now,currentAnalysis=null,meta={}){for(const s of engine.history){if(s.result==='PENDING'&&s.entryLocked&&now>=s.expiry){const d=price-s.entry;s.exit=price;s.exitSource=meta.source||null;s.exitBid=meta.bid??null;s.exitAsk=meta.ask??null;s.priceDifference=d;s.result=d===0?'TIE':(s.direction==='BUY'?d>0:d<0)?'WIN':'LOSS';s.resolvedAt=now;s.settlementRule='ANY_FAVORABLE_DIFFERENCE_WINS';if(s.result==='LOSS'){engine.lastLossReview=diagnoseLoss(s,currentAnalysis);if(!s.isRecovery)scheduleRecovery(s)}}}}
function resolveExactBoundarySignal(s,candle,now){if(!s||s.result!=='PENDING')return;const realtimeEntry=Number(s.entry),entry=Number(candle.open),exit=Number(candle.close),d=exit-entry;if(!Number.isFinite(entry)||!Number.isFinite(exit))throw new Error('Authoritative boundary candle contains invalid prices');s.realtimeEntry=Number.isFinite(realtimeEntry)?realtimeEntry:null;s.realtimeEntrySource=s.entrySource||null;s.entry=entry;s.exit=exit;s.entrySource='TARGET_CANDLE_OPEN';s.exitSource='TARGET_CANDLE_CLOSE';s.entryBid=null;s.entryAsk=null;s.exitBid=null;s.exitAsk=null;s.priceDifference=d;s.result=d===0?'TIE':(s.direction==='BUY'?d>0:d<0)?'WIN':'LOSS';s.resolvedAt=now;s.settlementRule='EXACT_BOUNDARY_OPEN_TO_EXPIRY_CLOSE';s.settlementSource=candle.source||'TARGET_CANDLE_OHLC';s.settlementBars=candle.bars??null;s.settlementStartTime=candle.startTime??s.signalBoundary;s.settlementEndTime=candle.endTime??s.expiry;s.entryDriftFromRealtime=Number.isFinite(realtimeEntry)?Number((realtimeEntry-entry).toFixed(10)):null;s.authoritativeBoundarySettlement=true;s.settlementError=null;if(s.result==='LOSS'){engine.lastLossReview=diagnoseLoss(s,null);if(!s.isRecovery)scheduleRecovery(s)}}
async function settleAuthoritatively(signal,attempt=0){if(!signal||signal.result!=='PENDING')return;try{const candle=await getSettlementCandle(signal.pair,signal.signalBoundary,signal.expiry);resolveExactBoundarySignal(signal,candle,Date.now())}catch(e){if(attempt<4){signal.settlementError=`Boundary settlement retry ${attempt+1}: ${e.message}`;setTimeout(()=>settleAuthoritatively(signal,attempt+1),700*(attempt+1))}else{signal.settlementError=`Authoritative boundary settlement failed after 5 attempts: ${e.message}`;signal.settlementPendingReview=true}}}
async function enrichLive(result,pair,horizon){if(microstructureSupported(pair)){try{return applyMicrostructure(result,await getMicrostructureSnapshot(pair))}catch{return result}}const tick=getForexTickConfirmation(pair);return tick?applyForexTickConfirmation(result,tick,horizon):result}
function scheduleCycle(){clearTimer();if(!engine.running)return;const offsets=sampleOffsets[engine.horizon]||sampleOffsets[1],boundary=nextFullBoundary(engine.horizon);engine.targetBoundary=boundary;engine.nextRunAt=boundary;engine.snapshots=[];engine.sampleStage=0;engine.phase='WAITING_SAMPLE';engine.sampleNextAt=boundary-offsets[0];engine.timer=setTimeout(takeSample,Math.max(100,engine.sampleNextAt-Date.now()))}
function scheduleNextSample(){const offsets=sampleOffsets[engine.horizon]||sampleOffsets[1];if(engine.sampleStage>=offsets.length)return finalizeCycle();engine.sampleNextAt=engine.targetBoundary-offsets[engine.sampleStage];engine.phase=`SAMPLING_${engine.sampleStage+1}_OF_3`;engine.timer=setTimeout(takeSample,Math.max(100,engine.sampleNextAt-Date.now()))}
async function takeSample(){if(!engine.running||engine.busy)return;engine.busy=true;let failed=false;try{const rawBundle=await getStagedSnapshot(engine.pair),bundle=timeframeBundle(rawBundle,engine.horizon),base=analyze(bundle,engine.horizon,engine.pair),enriched=await enrichLive(base,engine.pair,engine.horizon),result=fuseDecision(enriched,bundle,engine.pair,engine.horizon,MIN_CONFIDENCE),last=bundle.m1.at(-1);engine.snapshots.push({...result,pair:engine.pair,symbol:marketSymbol(engine.pair),analysisTimeframe:bundle.analysisTimeframe||`${engine.horizon}M`,candleTime:last?.time,sampleNumber:engine.sampleStage+1});engine.sampleStage++}catch(e){failed=true;engine.lastError=e.message}finally{engine.busy=false;if(engine.running){if(failed)setTimeout(scheduleCycle,3000);else if(engine.sampleStage>=3)finalizeCycle();else scheduleNextSample()}}}
function scoreFromEvidence(a){a=Math.abs(a);if(a<.15)return 50+a/.15*5;if(a<.30)return 55+(a-.15)/.15*5;if(a<.48)return 60+(a-.30)/.18*6;if(a<.66)return 66+(a-.48)/.18*6;if(a<.82)return 72+(a-.66)/.16*4;return 76+Math.min(3,(a-.82)/.18*3)}
function snapshotEvidence(s){if(String(s.engine||'').includes('FUSION_V1')){const dir=s.direction==='BUY'?1:-1;return dir*clamp((Number(s.confidence||50)-50)/35,0,1)}if(Number.isFinite(Number(s.evidenceScore)))return clamp(Number(s.evidenceScore),-1,1);const dir=s.direction==='BUY'?1:-1;return dir*clamp((Number(s.confidence||50)-50)/30,0,1)}
function blendedDecision(snaps){const final=snaps.at(-1);if(!final)return null;const w=[.18,.30,.52],ev=snaps.map(snapshotEvidence);let evidence=ev.reduce((a,v,i)=>a+v*(w[i]||0),0);const dirs=ev.map(v=>v>=0?'BUY':'SELL'),same=dirs.every(d=>d===dirs[0]),finalDir=ev.at(-1)>=0?1:-1,firstDir=ev[0]>=0?1:-1,trend=same?'CONSISTENT':finalDir!==firstDir?'REVERSING':'MIXED',strengthening=Math.abs(ev.at(-1))>Math.abs(ev[0])+.08&&finalDir===firstDir;if(same)evidence+=finalDir*.055;if(strengthening)evidence+=finalDir*.035;if(trend==='REVERSING')evidence*=.66;else if(trend==='MIXED')evidence*=.82;const f=final.features||{},allTicks=f.allTickWindowsAgree===true,persist=Number(f.tickPersistence||0),tickReverse=f.tickReversal===true,mtfAgree=Number(f.mtfAgreementCount||0),mtfOppose=Number(f.mtfOppositionCount||0);if(allTicks&&persist>=.75)evidence+=finalDir*.045;if(mtfAgree>=2)evidence+=finalDir*.035;if(mtfOppose>=2)evidence-=finalDir*.045;if(tickReverse)evidence*=.78;if(final.regime==='CHOPPY')evidence*=.84;else if(final.regime==='MIXED')evidence*=.94;evidence=clamp(evidence,-1,1);const direction=evidence>=0?'BUY':'SELL';let confidence=scoreFromEvidence(evidence);if(trend==='REVERSING')confidence-=2;if(tickReverse)confidence-=1.5;if(same&&strengthening&&allTicks)confidence+=1.5;if(Number(f.moveQualityScore||5)<5)confidence-=2;if(f.failureToProgress===true&&direction===final.direction)confidence-=2;confidence=clamp(confidence,50,82);const qualityScore=clamp(Math.abs(evidence)*70+(same?8:0)+(strengthening?6:0)+(allTicks?6:0)+(mtfAgree>=2?5:0)-(tickReverse?10:0)-(mtfOppose>=2?6:0),0,100),qualityGate=f.fusionQualityGate!==false;return{...final,direction,confidence:Number(confidence.toFixed(1)),qualityScore:Number(qualityScore.toFixed(1)),evidenceScore:Number(evidence.toFixed(4)),qualified:confidence>=MIN_CONFIDENCE&&qualityGate,minimumConfidence:MIN_CONFIDENCE,engine:`${final.engine||'TECHNICAL'}+3_STAGE_V4`,probabilityType:'integrated-fusion-forward-calibration-pending',features:{...f,snapshotEvolution:trend,snapshotDirections:dirs.join('>'),snapshotStrengthening:strengthening,finalEvidenceScore:Number(evidence.toFixed(4)),finalQualityScore:Number(qualityScore.toFixed(1)),analysisTimeframe:final.analysisTimeframe||`${engine.horizon}M`}}}
async function lockEntryAtBoundary(signal){const d=Math.max(0,signal.signalBoundary-Date.now()+50);if(d)await new Promise(r=>setTimeout(r,d));try{const x=await precisePrice(signal.pair);signal.entry=x.price;signal.entrySource=x.source;signal.entryBid=x.bid??null;signal.entryAsk=x.ask??null;signal.entryLocked=true;signal.expiry=signal.signalBoundary+signal.horizon*60000}catch(e){signal.entryError=e.message}}
function scheduleSettlement(signal){setTimeout(()=>settleAuthoritatively(signal),Math.max(250,signal.expiry-Date.now()+650))}
function finalizeCycle(){if(!engine.running)return;const b=blendedDecision(engine.snapshots);if(!b)return scheduleCycle();const adapted=applyLossContext(b,engine.pair,engine.horizon),r=adapted.result;engine.lastAnalysis=r;const boundary=engine.targetBoundary;if(r.qualified&&Number(r.confidence)>=MIN_CONFIDENCE&&engine.runSignals<TARGET_SIGNALS){const s={id:`${engine.runId}-${boundary}`,runId:engine.runId,pair:engine.pair,horizon:engine.horizon,analysisTimeframe:r.analysisTimeframe||r.features?.analysisTimeframe||`${engine.horizon}M`,direction:r.direction,probability:r.confidence,qualityScore:r.qualityScore??null,evidenceScore:r.evidenceScore??null,signalBoundary:boundary,entry:null,entryLocked:false,expiry:boundary+engine.horizon*60000,result:'PENDING',regime:r.regime,engine:r.engine,features:r.features,quotexRule:true,isRecovery:false};engine.history.unshift(s);engine.history=engine.history.slice(0,20);engine.runSignals++;lockEntryAtBoundary(s).then(()=>{if(s.entryLocked)scheduleSettlement(s)})}if(engine.runSignals>=TARGET_SIGNALS){engine.running=false;engine.phase='PAUSED_20';clearTimer()}else scheduleCycle()}
function startEngine(pair,horizon){clearTimer();engine.runId++;engine.runSignals=0;engine.pair=pair;engine.horizon=horizon;engine.running=true;engine.phase='RUNNING';engine.snapshots=[];engine.recoveryPending=null;engine.startedAt=Date.now();scheduleCycle()}
function stopEngine(){clearTimer();engine.running=false;engine.phase='STOPPED';engine.recoveryPending=null;engine.pausedAt=Date.now()}
async function runBtcResearch(){try{await getMicrostructureSnapshot('BTCUSD');researchRunner.lastRunAt=Date.now();researchRunner.lastError=null}catch(e){researchRunner.lastError=e.message}}
function startBtcResearch(){const delay=Math.max(1000,60000-Date.now()%60000+1200);researchRunner.timer=setTimeout(()=>{runBtcResearch();researchRunner.timer=setInterval(runBtcResearch,60000)},delay)}
function candleWindow(series,t,span){if(!Array.isArray(series)||!series.length)return[];const idx=series.reduce((best,x,i)=>Math.abs(Number(x.time)-t)<Math.abs(Number(series[best]?.time??Infinity)-t)?i:best,0);return series.slice(Math.max(0,idx-span),Math.min(series.length,idx+span+1))}
app.get('/api/time',(_q,r)=>r.json({serverTime:Date.now(),timezone:'UTC',source:'SERVER'}));
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'Forex Falcon',serverTime:Date.now(),budget:getBudget(),engine:publicState()}));
app.get('/api/config',(_q,r)=>r.json({title:'Next Candle Intelligence',pairs,horizons,minimumProbability:MIN_CONFIDENCE,targetSignals:TARGET_SIGNALS,thresholdValidation:{active:true,baseline:62,test:57,hypothesis:'Earlier qualifying entries may avoid late-move exhaustion while V2.5 invalidation guards remain active.'},recovery:{enabled:true,maxSteps:1,sameDirection:true,immediateNextCandle:true,recursive:false},settlement:{mode:'EXACT_BOUNDARY_OPEN_TO_EXPIRY_CLOSE',authoritativeSource:'TARGET_CANDLE_OHLC',tieRule:'EXACT_EQUALITY_ONLY',retryWithoutFallback:true},backgroundResearch:{automatic:true,mode:'independent-timeframe-boundary-validation',scanEveryMs:500,preBoundaryAnalysisMs:5000,defaultHorizonMinutes:1,perPairSelection:true,forcedCadence:false,independentAllTimeframesForSelectedPair:true,primeAllPairsOnStart:true},forexStrategy:{tickEngine:'BIQUOTE_SIGNALR_V3',multiWindowSeconds:[5,10,20,30],horizonAware:true,scoreArchitecture:'integrated-fusion-v1',forwardCalibrationPending:true}}));
app.get('/api/budget',(_q,r)=>r.json(getBudget()));
app.get('/api/engine/state',(_q,r)=>r.json(publicState()));
app.get('/api/research/background',(_q,r)=>r.json(getAllBackgroundResearch()));
app.get('/api/research/background/:pair',(q,r)=>r.json(getBackgroundResearch(q.params.pair,q.query.horizon??null)));
app.post('/api/research/background/:pair/horizon',(q,r)=>{try{const p=String(q.params.pair||'').toUpperCase(),h=Number(q.body?.horizon);if(!horizons.includes(h))return r.status(400).json({error:'Invalid horizon'});r.json(setBackgroundHorizon(p,h))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/research/btc',(_q,r)=>r.json({stats:getMicrostructureResearch('BTCUSD'),runner:researchRunner}));
app.get('/api/forex-ticks',(_q,r)=>r.json(getForexTickStatus()));
app.post('/api/engine/start',(q,r)=>{const pair=String(q.body?.pair||'').toUpperCase(),h=Number(q.body?.horizon);if(!pairs.includes(pair)||!horizons.includes(h))return r.status(400).json({error:'Invalid pair or horizon'});primeAllPairs().catch(()=>{});setBackgroundHorizon(pair,h);startEngine(pair,h);r.json(publicState())});
app.post('/api/engine/stop',(_q,r)=>{stopEngine();r.json(publicState())});
app.get('/api/analyze/:pair',async(q,r)=>{try{const pair=q.params.pair.toUpperCase(),h=Number(q.query.horizon||1);if(!pairs.includes(pair)||!horizons.includes(h))return r.status(400).json({error:'Invalid pair or horizon'});const rawBundle=await getStagedSnapshot(pair),bundle=timeframeBundle(rawBundle,h),enriched=await enrichLive(analyze(bundle,h,pair),pair,h),result=fuseDecision(enriched,bundle,pair,h,MIN_CONFIDENCE);r.json({...result,pair,horizon:h,analysisTimeframe:bundle.analysisTimeframe||`${h}M`,features:{...(result.features||{}),analysisTimeframe:bundle.analysisTimeframe||`${h}M`}})}catch(e){r.status(503).json({error:e.message})}});
app.get('/api/diagnostics/recent',async(_q,r)=>{try{const bundle=await getStagedSnapshot(engine.pair),signals=engine.history.slice(0,20).map(s=>({id:s.id,runId:s.runId,pair:s.pair,horizon:s.horizon,analysisTimeframe:s.analysisTimeframe,direction:s.direction,probability:s.probability,qualityScore:s.qualityScore,evidenceScore:s.evidenceScore,signalBoundary:s.signalBoundary,entry:s.entry,exit:s.exit,priceDifference:s.priceDifference,result:s.result,regime:s.regime,engine:s.engine,features:s.features,entrySource:s.entrySource,exitSource:s.exitSource,realtimeEntry:s.realtimeEntry,realtimeEntrySource:s.realtimeEntrySource,entryDriftFromRealtime:s.entryDriftFromRealtime,settlementRule:s.settlementRule,settlementSource:s.settlementSource,settlementBars:s.settlementBars,authoritativeBoundarySettlement:s.authoritativeBoundarySettlement,expiry:s.expiry,resolvedAt:s.resolvedAt,isRecovery:s.isRecovery,recoveryStep:s.recoveryStep,recoveryParentId:s.recoveryParentId,candles:{m1:candleWindow(bundle.m1,s.signalBoundary,6),m5:candleWindow(bundle.m5,s.signalBoundary,3),m15:candleWindow(bundle.m15,s.signalBoundary,2),h1:candleWindow(bundle.h1,s.signalBoundary,1)}}));r.json({pair:engine.pair,horizon:engine.horizon,serverTime:Date.now(),lastLossReview:engine.lastLossReview,adaptiveContext:getLossContext(engine.pair,engine.horizon),lastAnalysis:engine.lastAnalysis,signalCount:signals.length,signals})}catch(e){r.status(503).json({error:e.message})}});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>{console.log(`Forex Falcon running on port ${PORT}`);setTimeout(()=>{startForexTickStream().catch(()=>{});startBtcResearch();startBackgroundResearch()},500)});
