import {getStagedSnapshot,getSettlementPrice,marketSymbol} from './marketData.js';
import {analyze} from './analysis.js';
import {getForexTickConfirmation,applyForexTickConfirmation,getForexLivePrice} from './forexTicks.js';
import {microstructureSupported,getMicrostructureSnapshot,applyMicrostructure} from './microstructure.js';

const pairs=['EURUSD','EURJPY','GBPUSD','AUDJPY','AUDUSD','USDJPY','NZDCHF','USDPKR','USDINR','BTCUSD','XAUUSD'];
const allowedHorizons=new Set([1,2,3,5,15]);
const states=new Map(),timers=new Map(),preferredHorizon=new Map();
const SCAN_MS=1000,MIN_CONFIDENCE=60;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const key=(pair,h)=>`${pair}:${h}`;
function S(pair,horizon=1){pair=String(pair).toUpperCase();horizon=Number(horizon)||1;const k=key(pair,horizon);if(!states.has(k))states.set(k,{pair,horizon,pending:[],resolved:[],lastRunAt:null,lastError:null,running:false,targetBoundary:null,candidate:null,displaySignal:null,scans:0,qualifiedScans:0,primedAt:null,cycleStartedAt:null});return states.get(k)}
function streaks(rows){let w=0,l=0,mw=0,ml=0;for(const x of rows){if(x.result==='WIN'){w++;l=0;mw=Math.max(mw,w)}else if(x.result==='LOSS'){l++;w=0;ml=Math.max(ml,l)}}return{maxWinStreak:mw,maxLossStreak:ml}}
function oneStats(s){const r=s.resolved.filter(x=>x.qualified===true&&Number(x.confidence)>=MIN_CONFIDENCE),w=r.filter(x=>x.result==='WIN').length,l=r.filter(x=>x.result==='LOSS').length,t=r.filter(x=>x.result==='TIE').length;return{pair:s.pair,horizon:s.horizon,mode:'INDEPENDENT_TIMEFRAME_CYCLE',scanEveryMs:SCAN_MS,minimumConfidence:MIN_CONFIDENCE,scans:s.scans,qualifiedScans:s.qualifiedScans,currentCandidate:s.candidate,displaySignal:s.displaySignal,sample:r.length,pending:s.pending.filter(x=>x.qualified).length,wins:w,losses:l,ties:t,accuracy:w+l?w/(w+l):null,...streaks(r),last:r.at(-1)||null,recent:r.slice(-20).reverse(),lastRunAt:s.lastRunAt,lastError:s.lastError,running:s.running,primedAt:s.primedAt,targetBoundary:s.targetBoundary,cycleStartedAt:s.cycleStartedAt}}
function pairStats(pair){pair=String(pair).toUpperCase();const h=preferredHorizon.get(pair)||1,primary=oneStats(S(pair,h)),horizons={};for(const hh of allowedHorizons){const s=states.get(key(pair,hh));if(s)horizons[hh]=oneStats(s)}return{...primary,horizons}}
async function enrich(result,pair,h){if(microstructureSupported(pair)){try{return applyMicrostructure(result,await getMicrostructureSnapshot(pair))}catch{return result}}const tick=getForexTickConfirmation(pair);return tick?applyForexTickConfirmation(result,tick,h):result}
async function precisePrice(pair){const live=getForexLivePrice(pair,5000);if(live)return live;const x=await getSettlementPrice(pair);return{...x,source:'CANDLE_FALLBACK'}}
function aggregateM1(candles,minutes){const span=minutes*60000,now=Date.now(),out=[];for(const x of candles||[]){const t=Math.floor(Number(x.time)/span)*span;if(t+span>now-250)continue;let b=out.at(-1);if(!b||b.time!==t){b={time:t,open:x.open,high:x.high,low:x.low,close:x.close,volume:Number(x.volume||0)};out.push(b)}else{b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=Number(x.volume||0)}}return out}
function timeframeBundle(bundle,horizon){const h=Number(horizon)||1;if(h===1)return{...bundle,analysisTimeframe:'1M'};if(h===2){const base=aggregateM1(bundle.m1,2);return{...bundle,m1:base,m5:base,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'2M'}}if(h===3){const base=aggregateM1(bundle.m1,3);return{...bundle,m1:base,m5:base,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'3M'}}if(h===5)return{...bundle,m1:bundle.m5,m5:bundle.m5,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'5M'};if(h===15)return{...bundle,m1:bundle.m15,m5:bundle.m15,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'15M'};return bundle}
async function settle(s){if(!s.pending.length)return;const now=Date.now();if(!s.pending.some(p=>now>=p.expiry))return;let x;try{x=await precisePrice(s.pair)}catch(e){s.lastError=`settlement: ${e.message}`;return}const keep=[];for(const p of s.pending){if(now<p.expiry){keep.push(p);continue}const d=x.price-p.entry,result=d===0?'TIE':(p.direction==='BUY'?d>0:d<0)?'WIN':'LOSS';s.resolved.push({...p,exit:x.price,exitSource:x.source,exitBid:x.bid??null,exitAsk:x.ask??null,priceDifference:d,result,resolvedAt:now,settlementRule:'ANY_FAVORABLE_DIFFERENCE_WINS'})}s.pending=keep;s.resolved=s.resolved.slice(-5000)}
async function analyzeFresh(s,cycleStart,target){s.scans++;try{const rawBundle=await getStagedSnapshot(s.pair),bundle=timeframeBundle(rawBundle,s.horizon);let r=await enrich(analyze(bundle,s.horizon,''),s.pair,s.horizon);const confidence=Number(clamp(Number(r.confidence)||50,50,100).toFixed(1)),qualified=confidence>=MIN_CONFIDENCE;if(qualified)s.qualifiedScans++;const sig={pair:s.pair,horizon:s.horizon,analysisTimeframe:bundle.analysisTimeframe||`${s.horizon}M`,boundary:target,cycleStartedAt:cycleStart,direction:r.direction,confidence,qualified,generatedAt:Date.now(),regime:r.regime,engine:`${r.engine||'TECHNICAL'}_${bundle.analysisTimeframe||`${s.horizon}M`}`,features:{...(r.features||{}),analysisTimeframe:bundle.analysisTimeframe||`${s.horizon}M`},forexTicks:r.forexTicks||null};s.candidate=sig;s.displaySignal=sig;s.lastRunAt=Date.now();s.lastError=null;s.primedAt=s.primedAt||s.lastRunAt;return sig}catch(e){s.lastError=e.message;return null}}
async function beginCycle(s){await settle(s);const cycleStart=Date.now(),target=cycleStart+s.horizon*60000;s.cycleStartedAt=cycleStart;s.targetBoundary=target;s.candidate=null;s.displaySignal=null;const sig=await analyzeFresh(s,cycleStart,target);if(sig?.qualified){try{const entry=await precisePrice(s.pair);s.pending.push({id:`${s.pair}-${s.horizon}-${cycleStart}`,pair:s.pair,symbol:marketSymbol(s.pair),horizon:s.horizon,analysisTimeframe:sig.analysisTimeframe,predictedAt:sig.generatedAt,signalBoundary:cycleStart,entry:entry.price,entrySource:entry.source,entryBid:entry.bid??null,entryAsk:entry.ask??null,entryLockedAt:Date.now(),expiry:target,direction:sig.direction,confidence:sig.confidence,qualified:true,minimumConfidence:MIN_CONFIDENCE,regime:sig.regime,engine:sig.engine,features:sig.features,result:'PENDING',quotexRule:true,validationMode:'QUALIFIED'})}catch(e){s.lastError=`entry: ${e.message}`}}s.candidate=null}
async function scanState(s){if(!s.running)return;await settle(s);if(!s.targetBoundary||Date.now()>=s.targetBoundary-50)await beginCycle(s);const left=Math.max(100,s.targetBoundary-Date.now());timers.set(key(s.pair,s.horizon),setTimeout(()=>scanState(s),Math.min(SCAN_MS,left)))}
function startState(pair,horizon,forceFresh=false){const s=S(pair,horizon),k=key(pair,horizon);if(forceFresh&&timers.has(k)){clearTimeout(timers.get(k));timers.delete(k)}if(!s.running)s.running=true;if(forceFresh||!s.targetBoundary){beginCycle(s).finally(()=>{if(s.running&&!timers.has(k))timers.set(k,setTimeout(()=>scanState(s),SCAN_MS))})}else if(!timers.has(k))timers.set(k,setTimeout(()=>scanState(s),SCAN_MS));return s}
export async function primeAllPairs(){const ss=pairs.map(p=>{const h=preferredHorizon.get(p)||1;preferredHorizon.set(p,h);return startState(p,h,false)});await Promise.allSettled(ss.map(async s=>{if(!s.displaySignal)await beginCycle(s)}));return pairs.map(pairStats)}
export function setBackgroundHorizon(pair,horizon){pair=String(pair).toUpperCase();horizon=Number(horizon);if(!pairs.includes(pair))throw new Error('Unsupported background research pair');if(!allowedHorizons.has(horizon))throw new Error('Unsupported horizon');preferredHorizon.set(pair,horizon);const s=startState(pair,horizon,true);return oneStats(s)}
export function getBackgroundHorizon(pair){return preferredHorizon.get(String(pair).toUpperCase())||1}
export function startBackgroundResearch(){for(const p of pairs){const h=preferredHorizon.get(p)||1;preferredHorizon.set(p,h);startState(p,h,false)}}
export function stopBackgroundResearch(){for(const [k,t] of timers){clearTimeout(t);const s=states.get(k);if(s)s.running=false}timers.clear()}
export function getBackgroundResearch(pair,horizon=null){pair=String(pair).toUpperCase();if(horizon!=null)return oneStats(S(pair,Number(horizon)));return pairStats(pair)}
export function getAllBackgroundResearch(){return pairs.map(pairStats)}
