import {getStagedSnapshot,getSettlementPrice,getSettlementCandle,marketSymbol} from './marketData.js';
import {analyze} from './analysis.js';
import {fuseDecision} from './decisionFusion.js';
import {getForexTickConfirmation,applyForexTickConfirmation,getForexLivePrice} from './forexTicks.js';
import {microstructureSupported,getMicrostructureSnapshot,applyMicrostructure} from './microstructure.js';

const pairs=['EURUSD','EURJPY','GBPUSD','AUDJPY','AUDUSD','USDJPY','NZDCHF','USDPKR','USDINR','BTCUSD','XAUUSD'];
const allowedHorizons=new Set([1,2,3,5,15]);
const states=new Map(),timers=new Map(),preferredHorizon=new Map(),activePairs=new Set(pairs);
const SCAN_MS=500,MIN_CONFIDENCE=57,PRE_BOUNDARY_MS=10000,CANDIDATE_REFRESH_MS=1500,PREVIEW_MS=10000;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const key=(pair,h)=>`${pair}:${h}`;
function S(pair,horizon=1){pair=String(pair).toUpperCase();horizon=Number(horizon)||1;const k=key(pair,horizon);if(!states.has(k))states.set(k,{pair,horizon,pending:[],resolved:[],lastRunAt:null,lastPreviewAt:null,lastError:null,running:false,targetBoundary:null,candidate:null,displaySignal:null,scans:0,qualifiedScans:0,primedAt:null,cycleStartedAt:null,lastLockedBoundary:null,previewBusy:false});return states.get(k)}
function streaks(rows){let w=0,l=0,mw=0,ml=0;for(const x of rows){if(x.result==='WIN'){w++;l=0;mw=Math.max(mw,w)}else if(x.result==='LOSS'){l++;w=0;ml=Math.max(ml,l)}}return{maxWinStreak:mw,maxLossStreak:ml}}
function oneStats(s){const r=s.resolved.filter(x=>x.qualified===true&&Number(x.confidence)>=MIN_CONFIDENCE),pendingRows=s.pending.filter(x=>x.qualified===true&&Number(x.confidence)>=MIN_CONFIDENCE),w=r.filter(x=>x.result==='WIN').length,l=r.filter(x=>x.result==='LOSS').length,t=r.filter(x=>x.result==='TIE').length,recentResolved=r.slice(-20).reverse(),pendingRecent=pendingRows.slice(-20).reverse(),recentCombined=[...pendingRecent,...recentResolved].sort((a,b)=>Number(b.signalBoundary||b.predictedAt||0)-Number(a.signalBoundary||a.predictedAt||0)).slice(0,20);return{pair:s.pair,horizon:s.horizon,mode:'INDEPENDENT_TIMEFRAME_BOUNDARY_CYCLE+FUSION_V2',scanEveryMs:SCAN_MS,minimumConfidence:MIN_CONFIDENCE,scans:s.scans,qualifiedScans:s.qualifiedScans,currentCandidate:s.candidate,displaySignal:s.displaySignal,sample:r.length,pending:pendingRows.length,pendingRecent,recentCombined,wins:w,losses:l,ties:t,accuracy:w+l?w/(w+l):null,...streaks(r),last:r.at(-1)||null,recent:recentResolved,lastRunAt:s.lastRunAt,lastPreviewAt:s.lastPreviewAt,lastError:s.lastError,running:s.running,primedAt:s.primedAt,targetBoundary:s.targetBoundary,cycleStartedAt:s.cycleStartedAt,lastLockedBoundary:s.lastLockedBoundary}}
function pairStats(pair){pair=String(pair).toUpperCase();const h=preferredHorizon.get(pair)||1,primary=oneStats(S(pair,h)),horizons={};for(const hh of allowedHorizons){const s=states.get(key(pair,hh));if(s)horizons[hh]=oneStats(s)}return{...primary,horizons,allTimeframesActive:activePairs.has(pair)}}
async function enrich(result,pair,h){if(microstructureSupported(pair)){try{return applyMicrostructure(result,await getMicrostructureSnapshot(pair),h)}catch{return result}}const tick=getForexTickConfirmation(pair);return tick?applyForexTickConfirmation(result,tick,h):result}
async function precisePrice(pair){const live=getForexLivePrice(pair,5000);if(live)return live;const x=await getSettlementPrice(pair);return{...x,source:'CANDLE_FALLBACK'}}
function aggregateM1(candles,minutes){const span=minutes*60000,now=Date.now(),out=[];for(const x of candles||[]){const t=Math.floor(Number(x.time)/span)*span;if(t+span>now-250)continue;let b=out.at(-1);if(!b||b.time!==t){b={time:t,open:x.open,high:x.high,low:x.low,close:x.close,volume:Number(x.volume||0)};out.push(b)}else{b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=Number(x.volume||0)}}return out}
export function timeframeBundle(bundle,horizon){const h=Number(horizon)||1;if(h===1)return{...bundle,analysisTimeframe:'1M'};if(h===2){const base=aggregateM1(bundle.m1,2);return{...bundle,m1:base,m5:bundle.m5,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'2M'}}if(h===3){const base=aggregateM1(bundle.m1,3);return{...bundle,m1:base,m5:bundle.m5,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'3M'}}if(h===5)return{...bundle,m1:bundle.m5,m5:bundle.m5,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'5M'};if(h===15)return{...bundle,m1:bundle.m15,m5:bundle.m5,m15:bundle.m15,h1:bundle.h1,analysisTimeframe:'15M'};return{...bundle,analysisTimeframe:`${h}M`}}
function nextBoundary(h,now=Date.now()){const span=Number(h)*60000;return Math.ceil((now+250)/span)*span}
async function settle(s){if(!s.pending.length)return;const now=Date.now();if(!s.pending.some(p=>now>=p.expiry))return;let x;try{x=await precisePrice(s.pair)}catch(e){s.lastError=`settlement: ${e.message}`;return}const keep=[];for(const p of s.pending){if(now<p.expiry){keep.push(p);continue}let d=x.price-p.entry,result,settlementRule='ENTRY_TO_EXPIRY_PRICE',targetCandle=null;if(d===0){try{targetCandle=await getSettlementCandle(s.pair,p.signalBoundary,p.expiry);if(targetCandle.body!==0){const bullish=targetCandle.body>0;result=p.direction==='BUY'?(bullish?'WIN':'LOSS'):(bullish?'LOSS':'WIN');settlementRule='EXACT_PRICE_TIE_RESOLVED_BY_TARGET_CANDLE_BODY'}else result='TIE'}catch(e){s.lastError=`tie candle: ${e.message}`;result='TIE'}}else result=(p.direction==='BUY'?d>0:d<0)?'WIN':'LOSS';s.resolved.push({...p,exit:x.price,exitSource:x.source,exitBid:x.bid??null,exitAsk:x.ask??null,priceDifference:d,result,resolvedAt:now,settlementRule,settlementCandleOpen:targetCandle?.open??null,settlementCandleClose:targetCandle?.close??null,settlementCandleBody:targetCandle?.body??null,settlementCandleBars:targetCandle?.bars??null})}s.pending=keep;s.resolved=s.resolved.slice(-5000)}
function timeframeConfidence(raw,enriched,h){const tech=Number(raw?.confidence||50),live=Number(enriched?.confidence||tech),tw={1:.40,2:.52,3:.62,5:.78,15:.90}[Number(h)]||.62;return clamp(tech*tw+live*(1-tw),50,100)}
function makeSignal(s,bundle,raw,enriched,boundary,signalType){const confidence=Number(timeframeConfidence(raw,enriched,s.horizon).toFixed(1)),direction=enriched.direction||raw.direction,tf=bundle.analysisTimeframe||`${s.horizon}M`,last=bundle.m1.at(-1);return{pair:s.pair,horizon:s.horizon,analysisTimeframe:tf,signalType,boundary,cycleStartedAt:boundary-s.horizon*60000,direction,confidence,technicalConfidence:Number(raw.confidence||50),liveConfirmationConfidence:Number(enriched.confidence||raw.confidence||50),qualified:confidence>=MIN_CONFIDENCE,generatedAt:Date.now(),sourceCandleTime:last?.time??null,sourceCandleClose:last?.close??null,sourceCandleCount:bundle.m1.length,regime:enriched.regime||raw.regime,engine:`${enriched.engine||raw.engine||'TECHNICAL'}_${tf}+PRE_FUSION`,features:{...(enriched.features||raw.features||{}),horizon:s.horizon,analysisTimeframe:tf,sourceCandleTime:last?.time??null,sourceCandleClose:last?.close??null,sourceCandleCount:bundle.m1.length},forexTicks:enriched.forexTicks||null}}
async function computeAnalysis(s,boundary,signalType){const rawBundle=await getStagedSnapshot(s.pair),bundle=timeframeBundle(rawBundle,s.horizon),raw=analyze(bundle,s.horizon,s.pair),enriched=await enrich({...raw,horizon:s.horizon,features:{...(raw.features||{}),horizon:s.horizon,analysisTimeframe:bundle.analysisTimeframe||`${s.horizon}M`}},s.pair,s.horizon),baseSignal=makeSignal(s,bundle,raw,enriched,boundary,signalType);return fuseDecision(baseSignal,bundle,s.pair,s.horizon,MIN_CONFIDENCE)}
async function analyzeFresh(s,boundary){s.scans++;try{const sig=await computeAnalysis(s,boundary,'BOUNDARY_CANDIDATE');if(sig.qualified)s.qualifiedScans++;s.candidate=sig;s.displaySignal=sig;s.lastRunAt=Date.now();s.lastError=null;s.primedAt=s.primedAt||s.lastRunAt;s.cycleStartedAt=sig.cycleStartedAt;return sig}catch(e){s.lastError=e.message;return null}}
async function refreshDisplayAnalysis(s,force=false){if(s.previewBusy)return null;const now=Date.now();if(!force&&s.lastPreviewAt&&now-s.lastPreviewAt<PREVIEW_MS)return s.displaySignal;s.previewBusy=true;try{const boundary=s.targetBoundary||nextBoundary(s.horizon),sig=await computeAnalysis(s,boundary,'LIVE_TIMEFRAME_ANALYSIS');s.displaySignal=sig;s.lastPreviewAt=Date.now();s.lastRunAt=s.lastPreviewAt;s.lastError=null;s.primedAt=s.primedAt||s.lastRunAt;return sig}catch(e){s.lastError=e.message;return null}finally{s.previewBusy=false}}
function eligibleFallbackSignal(s,boundary){const sig=s.displaySignal;if(!sig?.qualified||Number(sig.confidence)<MIN_CONFIDENCE)return null;const g=Number(sig.generatedAt||0);if(!g||g>boundary||g<boundary-PRE_BOUNDARY_MS)return null;if(Number(sig.horizon)!==Number(s.horizon)||String(sig.pair||s.pair)!==s.pair)return null;return sig}
async function lockCandidateAtBoundary(s,boundary){if(s.lastLockedBoundary===boundary)return;const primary=s.candidate, fallback=eligibleFallbackSignal(s,boundary),sig=primary?.qualified&&Number(primary.confidence)>=MIN_CONFIDENCE?primary:fallback;s.lastLockedBoundary=boundary;if(sig){try{const entry=await precisePrice(s.pair),expiry=boundary+s.horizon*60000;s.pending.push({id:`${s.pair}-${s.horizon}-${boundary}`,pair:s.pair,symbol:marketSymbol(s.pair),horizon:s.horizon,analysisTimeframe:sig.analysisTimeframe,predictedAt:sig.generatedAt,signalBoundary:boundary,entry:entry.price,entrySource:entry.source,entryBid:entry.bid??null,entryAsk:entry.ask??null,entryLockedAt:Date.now(),expiry,direction:sig.direction,confidence:sig.confidence,qualified:true,minimumConfidence:MIN_CONFIDENCE,regime:sig.regime,engine:sig.engine,features:{...(sig.features||{}),boundaryLockSource:sig===primary?'BOUNDARY_CANDIDATE':'RECENT_DISPLAY_FALLBACK'},result:'PENDING',quotexRule:true,validationMode:'BOUNDARY_ALIGNED_QUALIFIED_FUSION_V2'})}catch(e){s.lastError=`entry: ${e.message}`}}s.candidate=null;s.targetBoundary=nextBoundary(s.horizon,boundary+250)}
async function scanState(s){if(!s.running)return;await settle(s);const now=Date.now();if(!s.targetBoundary||now>s.targetBoundary+s.horizon*60000)s.targetBoundary=nextBoundary(s.horizon,now);const boundary=s.targetBoundary,near=now>=boundary-PRE_BOUNDARY_MS&&now<boundary;if(near&&(!s.candidate||now-Number(s.candidate.generatedAt||0)>=CANDIDATE_REFRESH_MS))await analyzeFresh(s,boundary);if(!near&&preferredHorizon.get(s.pair)===s.horizon)await refreshDisplayAnalysis(s,false);if(now>=boundary&&s.lastLockedBoundary!==boundary)await lockCandidateAtBoundary(s,boundary);const wait=Math.max(100,Math.min(SCAN_MS,(s.targetBoundary||nextBoundary(s.horizon))-Date.now()));timers.set(key(s.pair,s.horizon),setTimeout(()=>scanState(s),wait))}
function startState(pair,horizon){const s=S(pair,horizon),k=key(pair,horizon);if(!s.running)s.running=true;if(!s.targetBoundary)s.targetBoundary=nextBoundary(horizon);if(!timers.has(k))timers.set(k,setTimeout(()=>scanState(s),50));return s}
function startPairAllHorizons(pair){pair=String(pair).toUpperCase();activePairs.add(pair);const out=[];for(const h of allowedHorizons)out.push(startState(pair,h));return out}
export async function primeAllPairs(){const ss=[];for(const p of pairs){const h=preferredHorizon.get(p)||1;preferredHorizon.set(p,h);ss.push(...startPairAllHorizons(p))}await Promise.allSettled(ss.filter(s=>preferredHorizon.get(s.pair)===s.horizon).map(s=>refreshDisplayAnalysis(s,true)));return pairs.map(pairStats)}
export function setBackgroundHorizon(pair,horizon){pair=String(pair).toUpperCase();horizon=Number(horizon);if(!pairs.includes(pair))throw new Error('Unsupported background research pair');if(!allowedHorizons.has(horizon))throw new Error('Unsupported horizon');preferredHorizon.set(pair,horizon);startPairAllHorizons(pair);const s=S(pair,horizon);refreshDisplayAnalysis(s,true).catch(()=>{});return oneStats(s)}
export function getBackgroundHorizon(pair){return preferredHorizon.get(String(pair).toUpperCase())||1}
export function startBackgroundResearch(){for(const p of pairs){const h=preferredHorizon.get(p)||1;preferredHorizon.set(p,h);startPairAllHorizons(p);refreshDisplayAnalysis(S(p,h),true).catch(()=>{})}}
export function stopBackgroundResearch(){for(const [k,t] of timers){clearTimeout(t);const s=states.get(k);if(s)s.running=false}timers.clear()}
export function getBackgroundResearch(pair,horizon=null){pair=String(pair).toUpperCase();if(horizon!=null)return oneStats(S(pair,Number(horizon)));return pairStats(pair)}
export function getAllBackgroundResearch(){return pairs.map(pairStats)}