const symbolMap={EURUSD:'EUR/USD',EURJPY:'EUR/JPY',GBPUSD:'GBP/USD',AUDJPY:'AUD/JPY',AUDUSD:'AUD/USD',USDJPY:'USD/JPY',NZDCHF:'NZD/CHF',USDPKR:'USD/PKR',USDINR:'USD/INR',BTCUSD:'BTC/USD',XAUUSD:'XAU/USD'};
const forexPairs=new Set(['EURUSD','EURJPY','GBPUSD','AUDJPY','AUDUSD','USDJPY','NZDCHF','USDPKR','USDINR']);
const DAILY_LIMIT=800,MINUTE_LIMIT=8;
const intervalMs={'1min':60_000,'5min':300_000,'15min':900_000,'1h':3_600_000};
const contextTtl={'5min':300_000,'15min':900_000,'1h':3_600_000};
let budgetDay='',creditsUsed=0,minuteKey='',minuteUsed=0,lastProviderUsed=null,lastProviderLeft=null,liveM1Used=0,contextUsed=0,settlementUsed=0,otherUsed=0;
let biquoteReads=0,biquoteFallbacks=0,lastForexProvider=null,lastForexProviderAt=null,lastForexError=null;
let krakenReads=0,lastBtcProviderAt=null,lastBtcError=null;
const contextCache=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function utcDay(){return new Date().toISOString().slice(0,10)}function utcMinute(){return new Date().toISOString().slice(0,16)}
function resetBudget(){const d=utcDay();if(d!==budgetDay){budgetDay=d;creditsUsed=0;liveM1Used=0;contextUsed=0;settlementUsed=0;otherUsed=0;biquoteReads=0;biquoteFallbacks=0;krakenReads=0;contextCache.clear();}}
function resetMinute(){const m=utcMinute();if(m!==minuteKey){minuteKey=m;minuteUsed=0;lastProviderUsed=null;lastProviderLeft=null}}function msToNextMinute(){return 60_000-(Date.now()%60_000)+350}
async function reserveOne(){resetBudget();resetMinute();if(creditsUsed>=DAILY_LIMIT)throw new Error('Daily Twelve Data trial limit reached (800/800). Resets at 00:00 UTC.');if(minuteUsed>=MINUTE_LIMIT){await sleep(msToNextMinute());resetMinute();}minuteUsed+=1;}
function normalize(values,interval,completedOnly=true){const now=Date.now(),dur=intervalMs[interval]||60_000;return values.map(v=>({time:new Date(String(v.datetime).replace(' ','T')+'Z').getTime(),open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close),volume:v.volume==null?null:Number(v.volume)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite)&&(!completedOnly||x.time+dur<=now-250)).sort((a,b)=>a.time-b.time);}
function normalizeBiquote(bars,interval,completedOnly=true){const now=Date.now(),dur=intervalMs[interval]||60_000;return bars.map(v=>({time:new Date(v.openTime).getTime(),open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close),volume:Number(v.tickVolume??v.volume??0)})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)&&(!completedOnly||x.time+dur<=now-250)).sort((a,b)=>a.time-b.time);}
function normalizeKraken(rows,interval,completedOnly=true){const now=Date.now(),dur=intervalMs[interval]||60_000;return rows.map(v=>({time:Number(v[0])*1000,open:Number(v[1]),high:Number(v[2]),low:Number(v[3]),close:Number(v[4]),volume:Number(v[6]??0)})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)&&(!completedOnly||x.time+dur<=now-250)).sort((a,b)=>a.time-b.time);}
function syncProviderHeaders(r){const used=Number(r.headers.get('api-credits-used')),left=Number(r.headers.get('api-credits-left'));if(Number.isFinite(used))lastProviderUsed=used;if(Number.isFinite(left))lastProviderLeft=left;}function countSuccess(purpose){creditsUsed+=1;if(purpose==='liveM1')liveM1Used+=1;else if(purpose==='context')contextUsed+=1;else if(purpose==='settlement')settlementUsed+=1;else otherUsed+=1;}
async function requestKraken(pair,interval,outputsize,{completedOnly=true}={}){if(pair!=='BTCUSD')throw new Error('Kraken candle route is BTCUSD only');const iv={'1min':1,'5min':5,'15min':15,'1h':60}[interval];if(!iv)throw new Error('Unsupported Kraken interval');const u=new URL('https://api.kraken.com/0/public/OHLC');u.searchParams.set('pair','XBTUSD');u.searchParams.set('interval',String(iv));const r=await fetch(u,{headers:{accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok){lastBtcError=`Kraken HTTP ${r.status}`;throw new Error(lastBtcError);}const j=await r.json();if(Array.isArray(j?.error)&&j.error.length){lastBtcError=`Kraken: ${j.error.join(', ')}`;throw new Error(lastBtcError);}const key=Object.keys(j?.result||{}).find(k=>k!=='last'),rows=key?j.result[key]:null;if(!Array.isArray(rows))throw new Error('Kraken OHLC unavailable');const data=normalizeKraken(rows.slice(-Math.min(720,outputsize)),interval,completedOnly);if(!data.length)throw new Error('Kraken returned no usable BTC candles');krakenReads+=1;lastBtcProviderAt=Date.now();lastBtcError=null;return data;}
async function requestBiquote(pair,interval,outputsize,{completedOnly=true}={}){const iv={'1min':'1m','5min':'5m','15min':'15m','1h':'1h'}[interval];if(!iv)throw new Error('Unsupported Biquote interval');const u=new URL(`https://biquote.io/api/${pair}/ohlc`);u.searchParams.set('interval',iv);u.searchParams.set('limit',String(Math.min(1000,outputsize)));const r=await fetch(u,{headers:{accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error(`Biquote HTTP ${r.status}`);const j=await r.json();if(!Array.isArray(j?.bars))throw new Error('Biquote OHLC unavailable');const data=normalizeBiquote(j.bars,interval,completedOnly);if(!data.length)throw new Error('Biquote returned no usable bars');biquoteReads+=1;lastForexProvider='BIQUOTE';lastForexProviderAt=Date.now();lastForexError=null;return data;}
async function requestTwelve(pair,interval,outputsize,{completedOnly=true,retry429=true,purpose='other'}={}){await reserveOne();const key=process.env.TWELVE_DATA_API_KEY;if(!key)throw new Error('TWELVE_DATA_API_KEY is not configured on the server');const symbol=symbolMap[pair];if(!symbol)throw new Error('Unsupported pair');const u=new URL('https://api.twelvedata.com/time_series');u.searchParams.set('symbol',symbol);u.searchParams.set('interval',interval);u.searchParams.set('outputsize',String(outputsize));u.searchParams.set('timezone','UTC');u.searchParams.set('apikey',key);const r=await fetch(u,{headers:{accept:'application/json'},cache:'no-store'});syncProviderHeaders(r);if(r.status===429){if(retry429){await sleep(msToNextMinute());resetMinute();return requestTwelve(pair,interval,outputsize,{completedOnly,retry429:false,purpose});}let detail='';try{const j=await r.json();detail=j?.message||''}catch{}throw new Error(detail?`Twelve Data rate limit: ${detail}`:'Twelve Data quota still exhausted after minute reset.');}if(!r.ok)throw new Error(`Market data HTTP ${r.status}`);const j=await r.json();if(j.status==='error'||!Array.isArray(j.values))throw new Error(j.message||'Market data unavailable');countSuccess(purpose);if(forexPairs.has(pair)){lastForexProvider='TWELVE_DATA_FALLBACK';lastForexProviderAt=Date.now();}return normalize(j.values,interval,completedOnly);}
async function requestSeries(pair,interval,outputsize,opts={}){if(pair==='BTCUSD')return requestKraken(pair,interval,outputsize,opts);if(forexPairs.has(pair)){try{return await requestBiquote(pair,interval,outputsize,opts);}catch(e){lastForexError=e.message;biquoteFallbacks+=1;return requestTwelve(pair,interval,outputsize,opts);}}return requestTwelve(pair,interval,outputsize,opts);}
function cacheKey(pair,interval){return `${pair}:${interval}`}function cacheFresh(entry,interval){if(!entry)return false;const ttl=contextTtl[interval]||60_000;return Date.now()-entry.fetchedAt<Math.max(30_000,ttl-5_000)}
async function getContext(pair,interval,outputsize){const key=cacheKey(pair,interval),hit=contextCache.get(key);if(cacheFresh(hit,interval))return hit.data;const data=await requestSeries(pair,interval,outputsize,{completedOnly:true,purpose:'context'});contextCache.set(key,{data,fetchedAt:Date.now()});return data;}
export async function warmContext(pair){const [m5,m15,h1]=await Promise.all([getContext(pair,'5min',220),getContext(pair,'15min',180),getContext(pair,'1h',120)]);return{m5,m15,h1};}
export async function getStagedSnapshot(pair){const m1=await requestSeries(pair,'1min',320,{completedOnly:false,purpose:'liveM1'});if(m1.length<80)throw new Error('Not enough M1 candles available');const [m5,m15,h1]=await Promise.all([getContext(pair,'5min',220),getContext(pair,'15min',180),getContext(pair,'1h',120)]);return{m1,m5,m15,h1,budget:getBudget(),snapshotAt:Date.now()};}
export async function getSettlementPrice(pair){const m1=await requestSeries(pair,'1min',3,{completedOnly:false,purpose:'settlement'});const x=m1.at(-1);if(!x)throw new Error('Settlement price unavailable');const rawPrice=x.close,body=x.close-x.open;let price=rawPrice,tieBreakApplied=false;if(body!==0){const epsilon=Math.max(Number.EPSILON*Math.max(1,Math.abs(rawPrice))*8,1e-12);price=rawPrice+Math.sign(body)*epsilon;tieBreakApplied=true}return{price,rawPrice,open:x.open,close:x.close,body,time:x.time,tieBreakApplied,budget:getBudget()};}
export function getBudget(){resetBudget();resetMinute();const dailyRemaining=Math.max(0,DAILY_LIMIT-creditsUsed);return{dailyLimit:DAILY_LIMIT,minuteLimit:MINUTE_LIMIT,creditsUsed,creditsRemaining:dailyRemaining,minuteUsed,minuteCreditsRemaining:Math.max(0,MINUTE_LIMIT-minuteUsed),providerMinuteUsed:lastProviderUsed,providerMinuteLeft:lastProviderLeft,usageBreakdown:{liveM1:liveM1Used,contextRefresh:contextUsed,settlement:settlementUsed,other:otherUsed},freeForex:{primary:'BIQUOTE',twelveDataRole:'FALLBACK',biquoteReads,biquoteFallbacks,lastProvider:lastForexProvider,lastProviderAt:lastForexProviderAt,lastError:lastForexError},btc:{primary:'KRAKEN',twelveDataUsed:false,krakenReads,lastProviderAt:lastBtcProviderAt,lastError:lastBtcError},minimumCreditsPerCompletedCycle:0,note:'Forex uses Biquote first with Twelve Data fallback. BTCUSD uses Kraken only for candles/settlement and Kraken order flow. XAUUSD remains on Twelve Data.',dayUTC:budgetDay};}
export function marketSymbol(pair){return pair==='BTCUSD'?'XBTUSD':symbolMap[pair]||pair;}
