const symbolMap={EURUSD:'EUR/USD',EURJPY:'EUR/JPY',GBPUSD:'GBP/USD',CADCHF:'CAD/CHF',USDJPY:'USD/JPY',NZDCHF:'NZD/CHF',USDPKR:'USD/PKR',USDINR:'USD/INR',BTCUSD:'BTC/USD',XAUUSD:'XAU/USD'};
const DAILY_LIMIT=800,MINUTE_LIMIT=8;
const intervalMs={'1min':60_000,'5min':300_000,'15min':900_000,'1h':3_600_000};
const contextTtl={'5min':300_000,'15min':900_000,'1h':3_600_000};
let budgetDay='',creditsUsed=0,minuteKey='',minuteUsed=0,lastProviderUsed=null,lastProviderLeft=null;
const contextCache=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function utcDay(){return new Date().toISOString().slice(0,10)}
function utcMinute(){return new Date().toISOString().slice(0,16)}
function resetBudget(){const d=utcDay();if(d!==budgetDay){budgetDay=d;creditsUsed=0}}
function resetMinute(){const m=utcMinute();if(m!==minuteKey){minuteKey=m;minuteUsed=0;lastProviderUsed=null;lastProviderLeft=null}}
function msToNextMinute(){return 60_000-(Date.now()%60_000)+350}
async function reserveOne(){resetBudget();resetMinute();if(creditsUsed>=DAILY_LIMIT)throw new Error('Daily Twelve Data trial limit reached (800/800). Resets at 00:00 UTC.');if(minuteUsed>=MINUTE_LIMIT){await sleep(msToNextMinute());resetMinute();}minuteUsed+=1;}
function normalize(values,interval,completedOnly=true){const now=Date.now(),dur=intervalMs[interval]||60_000;return values.map(v=>({time:new Date(String(v.datetime).replace(' ','T')+'Z').getTime(),open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close),volume:v.volume==null?null:Number(v.volume)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite)&&(!completedOnly||x.time+dur<=now-250)).sort((a,b)=>a.time-b.time);}
function syncProviderHeaders(r){const used=Number(r.headers.get('api-credits-used')),left=Number(r.headers.get('api-credits-left'));if(Number.isFinite(used))lastProviderUsed=used;if(Number.isFinite(left))lastProviderLeft=left;}
async function requestSeries(pair,interval,outputsize,{completedOnly=true,retry429=true}={}){await reserveOne();const key=process.env.TWELVE_DATA_API_KEY;if(!key)throw new Error('TWELVE_DATA_API_KEY is not configured on the server');const symbol=symbolMap[pair];if(!symbol)throw new Error('Unsupported pair');const u=new URL('https://api.twelvedata.com/time_series');u.searchParams.set('symbol',symbol);u.searchParams.set('interval',interval);u.searchParams.set('outputsize',String(outputsize));u.searchParams.set('timezone','UTC');u.searchParams.set('apikey',key);const r=await fetch(u,{headers:{accept:'application/json'},cache:'no-store'});syncProviderHeaders(r);if(r.status===429){if(retry429){await sleep(msToNextMinute());resetMinute();return requestSeries(pair,interval,outputsize,{completedOnly,retry429:false});}let detail='';try{const j=await r.json();detail=j?.message||''}catch{}throw new Error(detail?`Twelve Data rate limit: ${detail}`:'Twelve Data quota still exhausted after minute reset.');}if(!r.ok)throw new Error(`Market data HTTP ${r.status}`);const j=await r.json();if(j.status==='error'||!Array.isArray(j.values))throw new Error(j.message||'Market data unavailable');creditsUsed+=1;return normalize(j.values,interval,completedOnly);}
function cacheKey(pair,interval){return `${pair}:${interval}`}
function cacheFresh(entry,interval){if(!entry)return false;const ttl=contextTtl[interval]||60_000;return Date.now()-entry.fetchedAt<Math.max(30_000,ttl-5_000)}
async function getContext(pair,interval,outputsize){const key=cacheKey(pair,interval),hit=contextCache.get(key);if(cacheFresh(hit,interval))return hit.data;const data=await requestSeries(pair,interval,outputsize,{completedOnly:true});contextCache.set(key,{data,fetchedAt:Date.now()});return data;}
export async function warmContext(pair){const [m5,m15,h1]=await Promise.all([getContext(pair,'5min',220),getContext(pair,'15min',180),getContext(pair,'1h',120)]);return{m5,m15,h1};}
export async function getStagedSnapshot(pair){const m1=await requestSeries(pair,'1min',320,{completedOnly:false});if(m1.length<80)throw new Error('Not enough M1 candles available');const [m5,m15,h1]=await Promise.all([getContext(pair,'5min',220),getContext(pair,'15min',180),getContext(pair,'1h',120)]);return{m1,m5,m15,h1,budget:getBudget(),snapshotAt:Date.now()};}
export async function getSettlementPrice(pair){const m1=await requestSeries(pair,'1min',3,{completedOnly:false});const x=m1.at(-1);if(!x)throw new Error('Settlement price unavailable');return{price:x.close,time:x.time,budget:getBudget()};}
export function getBudget(){resetBudget();resetMinute();const dailyRemaining=Math.max(0,DAILY_LIMIT-creditsUsed);return{dailyLimit:DAILY_LIMIT,minuteLimit:MINUTE_LIMIT,liveM1ReadsPerCycle:3,creditsUsed,creditsRemaining:dailyRemaining,estimatedCyclesRemaining:Math.floor(dailyRemaining/3),minuteUsed,minuteCreditsRemaining:Math.max(0,MINUTE_LIMIT-minuteUsed),providerMinuteUsed:lastProviderUsed,providerMinuteLeft:lastProviderLeft,dayUTC:budgetDay};}
export function marketSymbol(pair){return symbolMap[pair]||pair;}
