const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const upper=v=>String(v||'').toUpperCase();
const round=(v,n=2)=>Number(Number(v||0).toFixed(n));
const directionalRows=rows=>(rows||[]).filter(x=>x&&(x.result==='WIN'||x.result==='LOSS'));

function currentLossRun(rows){let n=0;for(let i=rows.length-1;i>=0;i--){if(rows[i]?.result==='LOSS')n++;else if(rows[i]?.result==='WIN')break}return n}
function empirical(rows){const r=directionalRows(rows),wins=r.filter(x=>x.result==='WIN').length,n=r.length,priorN=25,priorP=.52,shrunk=(wins+priorN*priorP)/(n+priorN),reliability=n/(n+priorN);return{n,wins,losses:n-wins,rawAccuracy:n?wins/n:null,shrunkAccuracy:shrunk,reliability}}
function directionBias(rows){const r=directionalRows(rows).slice(-30),buy=r.filter(x=>upper(x.direction)==='BUY'),sell=r.filter(x=>upper(x.direction)==='SELL'),n=r.length,dominant=buy.length>=sell.length?'BUY':'SELL',dominantCount=Math.max(buy.length,sell.length),imbalance=n?dominantCount/n:0,side=a=>{const w=a.filter(x=>x.result==='WIN').length;return{n:a.length,accuracy:a.length?w/a.length:null}};return{window:n,buy:side(buy),sell:side(sell),dominantDirection:dominant,imbalance:round(imbalance,4),alarm:n>=12&&imbalance>=.80}}
function fingerprint(signal){const f=signal?.features||{};return [upper(signal?.direction),upper(signal?.regime),round(f.directionAlignedEvidence??f.directionalEvidenceScore??f.evidenceScore,1),round(f.progressScore,0),upper(f.groupConsensusDirection),round(f.groupDominance,1),upper(f.dynamicZoneSide),f.failureToProgress===true?'FAIL':'OK',f.emaCompression===true?'EC':'',f.bbContraction===true?'BC':'',upper(f.activeFvgState)].join('|')}
function freshness(signal,history){const fp=fingerprint(signal);const recent=(history||[]).slice(-4),same=recent.filter(x=>fingerprint(x)===fp).length,source=Number(signal?.sourceCandleTime||signal?.features?.sourceCandleTime||0),lastSource=Number(recent.at(-1)?.sourceCandleTime||recent.at(-1)?.features?.sourceCandleTime||0),sourceAdvanced=!source||!lastSource||source>lastSource;return{fingerprint:fp,repeatedRecent:same,sourceAdvanced,staleRisk:same>=2&&!sourceAdvanced,warning:same>=2?'REPEATED_EVIDENCE_FINGERPRINT':null}}
function lossDiagnosis(rows){const r=directionalRows(rows),run=currentLossRun(r);if(run<3)return{currentLossRun:run,active:false,recurrentTags:[]};const streak=r.slice(-run),counts=new Map();for(const x of streak){const tags=[...(x.features?.frequencyConflicts||[]),...(x.features?.frequencyStructuralTags||[]),...(x.vetoReasons||[]),upper(x.regime),upper(x.direction)].filter(Boolean);for(const t of new Set(tags))counts.set(t,(counts.get(t)||0)+1)}const recurrentTags=[...counts.entries()].filter(([,n])=>n>=Math.ceil(run*.5)).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([tag,count])=>({tag,count,share:round(count/run,3)}));return{currentLossRun:run,active:true,severity:run>=5?'CRITICAL':run>=4?'HIGH':'WATCH',recurrentTags}}
function regimeTrust(signal){const reg=upper(signal?.regime),f=signal?.features||{},progress=Number(f.progressScore||0)*(upper(signal?.direction)==='BUY'?1:-1),rejection=Math.max(Number(f.lastUpperWickRatio||0),Number(f.lastLowerWickRatio||0));if(reg==='CHOPPY')return{regime:reg,continuationTrust:.72,reactionTrust:1.12,notes:['CHOPPY_REDUCE_GENERIC_CONTINUATION','CHOPPY_FAVOR_LOCATION_REACTION']};if(reg==='TRENDING'||reg==='GREEN')return{regime:reg,continuationTrust:progress>0?1.12:.9,reactionTrust:rejection>=.38?.85:1,notes:['TREND_REQUIRE_PROGRESS']};return{regime:reg||'MIXED',continuationTrust:.92,reactionTrust:1,notes:['MIXED_REQUIRE_CONFIRMATION']}}
export function assessRuntimeQuality(signal,resolved=[],pending=[]){const profile=empirical(resolved),bias=directionBias(resolved),fresh=freshness(signal,[...(resolved||[]),...(pending||[])]),loss=lossDiagnosis(resolved),regime=regimeTrust(signal),calibratedProbability=clamp(.5+(profile.shrunkAccuracy-.5)*profile.reliability+(Number(signal?.confidence||57)-57)/250,.45,.68);return{version:'RUNTIME_QUALITY_V1',profile:{...profile,rawAccuracy:profile.rawAccuracy==null?null:round(profile.rawAccuracy,4),shrunkAccuracy:round(profile.shrunkAccuracy,4),reliability:round(profile.reliability,4)},calibratedProbability:round(calibratedProbability,4),directionBias:bias,freshness:fresh,lossStreak:loss,regimeTrust:regime,frequencyImpact:'NONE',authoritative:false}}
